"use strict";function e(e){return e&&"object"==typeof e&&"default"in e?e.default:e}var t=e(require("../config/config.default")),n=require("./auto-code"),s=e(require("path")),r=e(require("fs"));
/*! *****************************************************************************
Copyright (c) Microsoft Corporation.

Permission to use, copy, modify, and/or distribute this software for any
purpose with or without fee is hereby granted.

THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES WITH
REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY
AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY SPECIAL, DIRECT,
INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM
LOSS OF USE, DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR
OTHER TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR
PERFORMANCE OF THIS SOFTWARE.
***************************************************************************** */
function o(e,t,n,s){return new(n||(n=Promise))((function(r,o){function i(e){try{u(s.next(e))}catch(e){o(e)}}function c(e){try{u(s.throw(e))}catch(e){o(e)}}function u(e){var t;e.done?r(e.value):(t=e.value,t instanceof n?t:new n((function(e){e(t)}))).then(i,c)}u((s=s.apply(e,t||[])).next())}))}function i(){const e=Object.assign(Object.assign({controller:n.controllerList,service:n.serviceList},n.pluginList),{request:{},response:{},config:t});return Object.keys(n.serviceList).forEach(t=>{n.serviceList[t].ctx=e}),e}var c=Object.freeze({__proto__:null,W:class{constructor(e=null){this.app=e,this.headerMsg="[ - W - ]"}get(e,t){const n=i();this.app.get(e,(e,s)=>{n.request=e;const{hostname:r,url:o,headers:i,query:c,body:u,method:a,ip:p,ips:l,httpVersion:d,domain:h}=e;n.log.write(`${this.headerMsg}--get--request--\n${JSON.stringify({hostname:r,url:o,headers:i,query:c,body:u,method:a,ip:p,ips:l,httpVersion:d,domain:h})}`),t(n).then(()=>{n.log.write(`${this.headerMsg}--get--response--\n${JSON.stringify(n.response)}`),s.send(n.response)})})}post(e,t){const n=i();this.app.post(e,(e,s)=>{n.request=e;const{hostname:r,url:o,headers:i,query:c,body:u,method:a,ip:p,ips:l,httpVersion:d,domain:h}=e;n.log.write(`${this.headerMsg}--post--request--\n${JSON.stringify({hostname:r,url:o,headers:i,query:c,body:u,method:a,ip:p,ips:l,httpVersion:d,domain:h})}`),t(n).then(()=>{n.log.write(`${this.headerMsg}--post--response--\n${JSON.stringify(n.response)}`),s.send(n.response)})})}execute(e){return o(this,void 0,void 0,(function*(){const t=i();yield e(t),t.log.write("executed a task.")}))}}});function u(e){const t=e.split("");return t[0]=t[0].toLowerCase(),t.join("")}function a(e,t,n=!1){let s=e.filter(e=>"ts"===e.split(".")[1]),r=s.map(e=>{const n=e.split(".")[0];return`import ${n}${t} from '../${t}/${n}';`}),o=s.map(e=>{const n=e.split(".")[0];return`${u(n)}: ${n}${t},`});n||o.unshift("[key: string]: any"),o.unshift(`export type ${t}Type = {`),o.push("};");let i=s.map(e=>{const n=e.split(".")[0];return`${u(n)}: new ${n}${t}(),`}),c=`: ${t}Type`;return i.unshift(`export const ${t}List${c} = {`),i.push("};"),[...r,...o,...i].join("\n")}var p=Object.assign(Object.assign({},c),{boot:function(e="../"){console.log("boot start...");const t=s.resolve(__dirname,e+"controller"),n=s.resolve(__dirname,e+"service"),o=s.resolve(__dirname,e+"plugin"),i=r.readdirSync(t),c=r.readdirSync(n),u=r.readdirSync(o),p=a(i,"controller",!0),l=a(c,"service"),d=a(u,"plugin",!0);r.writeFileSync(s.resolve(__dirname,"./auto-code.ts"),["// auto generated //",p,l,d,"\n"].join("\n\n")),console.log("code generated."),console.log("boot done.")}});module.exports=p;
